name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Full-year calendar
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.isocalendar.fullyear.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_isocalendar: yes
        plugin_isocalendar_duration: full-year
        
    - name: Anime
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.anilist.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_anilist_user: HappyxSenpai
        plugin_anilist: yes
        plugin_anilist_sections: favorites, characters
        plugin_anilist_limit: 3
        plugin_anilist_limit_characters: 22
      
    - name: Steam
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.steam.full.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
        plugin_steam: yes
        plugin_steam_user: "76561198132876294"
        
    - name: MBTI Personality profile
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.16personalities.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_16personalities: yes
        plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
        plugin_16personalities_sections: personality, traits
        plugin_16personalities_scores: no
        
    - name: Icons
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.topics.icons.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_topics: yes
        plugin_topics_limit: 0
        plugin_topics_mode: icons
        
    - name: Detailed display
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.achievements.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_achievements: yes
        plugin_fortune: yes
        
        
